services:
  - type: web
    name: stud-fit-api
    env: docker
    plan: free
    region: oregon

    startCommand: java -jar app.jar

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: API_PORT
        value: 8080

      - key: HOST
        fromDatabase:
          name: stud-fit-db
          property: host

      - key: DB_USER
        fromDatabase:
          name: stud-fit-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: stud-fit-db
          property: password

      - key: REDIS_HOST
        fromService:
          type: redis
          name: stud-fit-cache
          property: host

      - key: REDIS_PORT
        fromService:
          type: redis
          name: stud-fit-cache
          property: port

      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_SESSION_TOKEN
        sync: false
      - key: AWS_BUCKET_ATESTADO
        sync: false

      - key: API_MAIL
        sync: false
      - key: API_PASSWORD
        sync: false

      - key: KEY
        sync: false

databases:
  - name: stud-fit-db
    databaseName: studfit
    user: studfituser
    plan: free
    region: oregon

  - name: stud-fit-cache
    type: redis
    plan: free
    region: oregon
    ipAllowList: []